pairs(USArrests,pch=20,lower.panel = NULL)
data("USArrests")
str(USArrests,vec.len=2)
library(skimr)
library(knitr)
knit_print(skim(USArrests))
cor.arrest<-cor(USArrests)
round(cor.arrest,2)
set.seed(1)
arrest.pca<-princomp(USArrests)
summary(arrest.pca)
biplot(arrest.pca,xlim=c(-0.3,0.4),cex=.7)
